# Generated by Django 5.2.7 on 2026-01-09 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=120)),
                ('game_key', models.CharField(choices=[('cards', 'Картки'), ('match_photo', 'Співпадання: Назва та Фото'), ('match_description', 'Співпадання: Назва та Опис'), ('chronology', 'Хронологія'), ('location', 'Де знаходиться?')], max_length=40)),
                ('best_score', models.IntegerField(default=0)),
                ('best_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GameBestResult',
        ),
        migrations.AddConstraint(
            model_name='gameresult',
            constraint=models.UniqueConstraint(fields=('user', 'region', 'game_key'), name='uniq_user_region_game'),
        ),
    ]
