# Generated by Django 5.2.7 on 2026-01-11 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_monumentimagesuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonumentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=120)),
                ('monument_id', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='monuments/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='monumentimagesuggestion',
            name='user_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='monumentimagesuggestion',
            index=models.Index(fields=['status', 'created_at'], name='map_app_mon_status_34a952_idx'),
        ),
        migrations.AddIndex(
            model_name='monumentimagesuggestion',
            index=models.Index(fields=['region', 'monument_id'], name='map_app_mon_region_2ce4e6_idx'),
        ),
        migrations.AddIndex(
            model_name='monumentphoto',
            index=models.Index(fields=['region', 'monument_id'], name='map_app_mon_region_e8c387_idx'),
        ),
    ]
