# Generated by Django 5.2.7 on 2026-01-14 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_monumentphoto_monumentimagesuggestion_user_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=120)),
                ('monument_id', models.SlugField(max_length=140)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='monuments/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monuments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['region', 'monument_id'], name='map_app_mon_region_63da08_idx'), models.Index(fields=['created_at'], name='map_app_mon_created_b0ea0e_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'monument_id'), name='uniq_region_monument_id')],
            },
        ),
        migrations.CreateModel(
            name='MonumentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('image', models.ImageField(upload_to='monuments/suggestions/')),
                ('status', models.CharField(choices=[('pending', 'Очікує модерації'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_monument_suggestions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monument_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='map_app_mon_status_a5360a_idx'), models.Index(fields=['region', 'created_at'], name='map_app_mon_region_7bf444_idx')],
            },
        ),
    ]
