# Generated by Django 5.2.7 on 2026-04-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0006_contactmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='map_app_con_status_293c4e_idx',
            old_name='map_app_con_status_0e2bb0_idx',
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='map_app_con_created_1b7a1e_idx',
            old_name='map_app_con_created_0b9d46_idx',
        ),
        migrations.AddField(
            model_name='monument',
            name='hint',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monument',
            name='is_game_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monument',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monument',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
