# Generated by Django 5.2.7 on 2026-04-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0007_rename_map_app_con_status_0e2bb0_idx_map_app_con_status_293c4e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='year_display',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
